sudo ./hubo-read-trajectory -s -f 100 -n valveH00O.traj
sudo ./hubo-read-trajectory -s -f 100 -n valve0.traj
sudo ./hubo-read-trajectory -s -f 100 -n valveH01C.traj
sudo ./hubo-read-trajectory -s -f 100 -n valve1.traj
sudo ./hubo-read-trajectory -s -f 100 -n valveH12O.traj
sudo ./hubo-read-trajectory -s -f 100 -n valve2.traj
sudo ./hubo-read-trajectory -s -f 100 -n valveH21C.traj
sudo ./hubo-read-trajectory -s -f 100 -n valve1.traj
sudo ./hubo-read-trajectory -s -f 100 -n valveH12O.traj
sudo ./hubo-read-trajectory -s -f 100 -n valve2.traj
sudo ./hubo-read-trajectory -s -f 100 -n valveH21C.traj
sudo ./hubo-read-trajectory -s -f 100 -n valve1.traj
sudo ./hubo-read-trajectory -s -f 100 -n valveH12O.traj
sudo ./hubo-read-trajectory -s -f 100 -n valve2.traj
sudo ./hubo-read-trajectory -s -f 100 -n valveH21C.traj
sudo ./hubo-read-trajectory -s -f 100 -n valve1.traj
sudo ./hubo-read-trajectory -s -f 100 -n valveH12O.traj
sudo ./hubo-read-trajectory -s -f 100 -n valve2.traj
sudo ./hubo-read-trajectory -s -f 100 -n valveH21C.traj
sudo ./hubo-read-trajectory -s -f 100 -n valve1.traj
sudo ./hubo-read-trajectory -s -f 100 -n valveH12O.traj
sudo ./hubo-read-trajectory -s -f 100 -n valve3.traj
