/* Auto-generated by genmsg_cpp for file /opt/ros/fuerte/stacks/maestro/hubomsg/msg/HuboCmd.msg */
#ifndef HUBOMSG_MESSAGE_HUBOCMD_H
#define HUBOMSG_MESSAGE_HUBOCMD_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace hubomsg
{
template <class ContainerAllocator>
struct HuboCmd_ {
  typedef HuboCmd_<ContainerAllocator> Type;

  HuboCmd_()
  : joint(0)
  , angle(0.0)
  , msg()
  {
  }

  HuboCmd_(const ContainerAllocator& _alloc)
  : joint(0)
  , angle(0.0)
  , msg(_alloc)
  {
  }

  typedef int64_t _joint_type;
  int64_t joint;

  typedef double _angle_type;
  double angle;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _msg_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  msg;


  typedef boost::shared_ptr< ::hubomsg::HuboCmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hubomsg::HuboCmd_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct HuboCmd
typedef  ::hubomsg::HuboCmd_<std::allocator<void> > HuboCmd;

typedef boost::shared_ptr< ::hubomsg::HuboCmd> HuboCmdPtr;
typedef boost::shared_ptr< ::hubomsg::HuboCmd const> HuboCmdConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::hubomsg::HuboCmd_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::hubomsg::HuboCmd_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace hubomsg

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::hubomsg::HuboCmd_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::hubomsg::HuboCmd_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::hubomsg::HuboCmd_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d5db4a16ad98b99e078cccd0e81d4786";
  }

  static const char* value(const  ::hubomsg::HuboCmd_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd5db4a16ad98b99eULL;
  static const uint64_t static_value2 = 0x078cccd0e81d4786ULL;
};

template<class ContainerAllocator>
struct DataType< ::hubomsg::HuboCmd_<ContainerAllocator> > {
  static const char* value() 
  {
    return "hubomsg/HuboCmd";
  }

  static const char* value(const  ::hubomsg::HuboCmd_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::hubomsg::HuboCmd_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int64 joint\n\
float64 angle\n\
string msg\n\
\n\
";
  }

  static const char* value(const  ::hubomsg::HuboCmd_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::hubomsg::HuboCmd_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.joint);
    stream.next(m.angle);
    stream.next(m.msg);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct HuboCmd_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hubomsg::HuboCmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::hubomsg::HuboCmd_<ContainerAllocator> & v) 
  {
    s << indent << "joint: ";
    Printer<int64_t>::stream(s, indent + "  ", v.joint);
    s << indent << "angle: ";
    Printer<double>::stream(s, indent + "  ", v.angle);
    s << indent << "msg: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.msg);
  }
};


} // namespace message_operations
} // namespace ros

#endif // HUBOMSG_MESSAGE_HUBOCMD_H

