/* Auto-generated by genmsg_cpp for file /opt/ros/fuerte/stacks/maestro/hubomsg/msg/HuboState.msg */
#ifndef HUBOMSG_MESSAGE_HUBOSTATE_H
#define HUBOMSG_MESSAGE_HUBOSTATE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "hubomsg/HuboJointState.h"
#include "hubomsg/HuboIMU.h"
#include "hubomsg/HuboIMU.h"
#include "hubomsg/HuboIMU.h"
#include "hubomsg/HuboFT.h"
#include "hubomsg/HuboFT.h"
#include "hubomsg/HuboFT.h"
#include "hubomsg/HuboFT.h"

namespace hubomsg
{
template <class ContainerAllocator>
struct HuboState_ {
  typedef HuboState_<ContainerAllocator> Type;

  HuboState_()
  : joints()
  , imu()
  , left_foot()
  , right_foot()
  , left_wrist()
  , right_wrist()
  , left_ankle()
  , right_ankle()
  , nsec(0)
  {
  }

  HuboState_(const ContainerAllocator& _alloc)
  : joints(_alloc)
  , imu(_alloc)
  , left_foot(_alloc)
  , right_foot(_alloc)
  , left_wrist(_alloc)
  , right_wrist(_alloc)
  , left_ankle(_alloc)
  , right_ankle(_alloc)
  , nsec(0)
  {
  }

  typedef std::vector< ::hubomsg::HuboJointState_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::hubomsg::HuboJointState_<ContainerAllocator> >::other >  _joints_type;
  std::vector< ::hubomsg::HuboJointState_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::hubomsg::HuboJointState_<ContainerAllocator> >::other >  joints;

  typedef  ::hubomsg::HuboIMU_<ContainerAllocator>  _imu_type;
   ::hubomsg::HuboIMU_<ContainerAllocator>  imu;

  typedef  ::hubomsg::HuboIMU_<ContainerAllocator>  _left_foot_type;
   ::hubomsg::HuboIMU_<ContainerAllocator>  left_foot;

  typedef  ::hubomsg::HuboIMU_<ContainerAllocator>  _right_foot_type;
   ::hubomsg::HuboIMU_<ContainerAllocator>  right_foot;

  typedef  ::hubomsg::HuboFT_<ContainerAllocator>  _left_wrist_type;
   ::hubomsg::HuboFT_<ContainerAllocator>  left_wrist;

  typedef  ::hubomsg::HuboFT_<ContainerAllocator>  _right_wrist_type;
   ::hubomsg::HuboFT_<ContainerAllocator>  right_wrist;

  typedef  ::hubomsg::HuboFT_<ContainerAllocator>  _left_ankle_type;
   ::hubomsg::HuboFT_<ContainerAllocator>  left_ankle;

  typedef  ::hubomsg::HuboFT_<ContainerAllocator>  _right_ankle_type;
   ::hubomsg::HuboFT_<ContainerAllocator>  right_ankle;

  typedef int64_t _nsec_type;
  int64_t nsec;


  typedef boost::shared_ptr< ::hubomsg::HuboState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hubomsg::HuboState_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct HuboState
typedef  ::hubomsg::HuboState_<std::allocator<void> > HuboState;

typedef boost::shared_ptr< ::hubomsg::HuboState> HuboStatePtr;
typedef boost::shared_ptr< ::hubomsg::HuboState const> HuboStateConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::hubomsg::HuboState_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::hubomsg::HuboState_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace hubomsg

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::hubomsg::HuboState_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::hubomsg::HuboState_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::hubomsg::HuboState_<ContainerAllocator> > {
  static const char* value() 
  {
    return "6bd9ae66c17e00532805d596fb489e84";
  }

  static const char* value(const  ::hubomsg::HuboState_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x6bd9ae66c17e0053ULL;
  static const uint64_t static_value2 = 0x2805d596fb489e84ULL;
};

template<class ContainerAllocator>
struct DataType< ::hubomsg::HuboState_<ContainerAllocator> > {
  static const char* value() 
  {
    return "hubomsg/HuboState";
  }

  static const char* value(const  ::hubomsg::HuboState_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::hubomsg::HuboState_<ContainerAllocator> > {
  static const char* value() 
  {
    return "HuboJointState[] joints\n\
HuboIMU imu\n\
HuboIMU left_foot\n\
HuboIMU right_foot\n\
HuboFT left_wrist\n\
HuboFT right_wrist\n\
HuboFT left_ankle\n\
HuboFT right_ankle\n\
int64 nsec\n\
\n\
================================================================================\n\
MSG: hubomsg/HuboJointState\n\
string name\n\
float64 commanded\n\
float64 position\n\
float64 velocity\n\
float64 current\n\
float64 temperature\n\
int32 active\n\
int32 zeroed\n\
int32 homed\n\
int32 status\n\
================================================================================\n\
MSG: hubomsg/HuboIMU\n\
float64 x_acceleration\n\
float64 y_acceleration\n\
float64 z_acceleration\n\
float64 x_rotation\n\
float64 y_rotation\n\
\n\
================================================================================\n\
MSG: hubomsg/HuboFT\n\
float64 Mx\n\
float64 My\n\
float64 Fz\n\
\n\
";
  }

  static const char* value(const  ::hubomsg::HuboState_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::hubomsg::HuboState_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.joints);
    stream.next(m.imu);
    stream.next(m.left_foot);
    stream.next(m.right_foot);
    stream.next(m.left_wrist);
    stream.next(m.right_wrist);
    stream.next(m.left_ankle);
    stream.next(m.right_ankle);
    stream.next(m.nsec);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct HuboState_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hubomsg::HuboState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::hubomsg::HuboState_<ContainerAllocator> & v) 
  {
    s << indent << "joints[]" << std::endl;
    for (size_t i = 0; i < v.joints.size(); ++i)
    {
      s << indent << "  joints[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::hubomsg::HuboJointState_<ContainerAllocator> >::stream(s, indent + "    ", v.joints[i]);
    }
    s << indent << "imu: ";
s << std::endl;
    Printer< ::hubomsg::HuboIMU_<ContainerAllocator> >::stream(s, indent + "  ", v.imu);
    s << indent << "left_foot: ";
s << std::endl;
    Printer< ::hubomsg::HuboIMU_<ContainerAllocator> >::stream(s, indent + "  ", v.left_foot);
    s << indent << "right_foot: ";
s << std::endl;
    Printer< ::hubomsg::HuboIMU_<ContainerAllocator> >::stream(s, indent + "  ", v.right_foot);
    s << indent << "left_wrist: ";
s << std::endl;
    Printer< ::hubomsg::HuboFT_<ContainerAllocator> >::stream(s, indent + "  ", v.left_wrist);
    s << indent << "right_wrist: ";
s << std::endl;
    Printer< ::hubomsg::HuboFT_<ContainerAllocator> >::stream(s, indent + "  ", v.right_wrist);
    s << indent << "left_ankle: ";
s << std::endl;
    Printer< ::hubomsg::HuboFT_<ContainerAllocator> >::stream(s, indent + "  ", v.left_ankle);
    s << indent << "right_ankle: ";
s << std::endl;
    Printer< ::hubomsg::HuboFT_<ContainerAllocator> >::stream(s, indent + "  ", v.right_ankle);
    s << indent << "nsec: ";
    Printer<int64_t>::stream(s, indent + "  ", v.nsec);
  }
};


} // namespace message_operations
} // namespace ros

#endif // HUBOMSG_MESSAGE_HUBOSTATE_H

