/* Auto-generated by genmsg_cpp for file /opt/ros/fuerte/stacks/maestro/hubomsg/msg/AchCommand.msg */
#ifndef HUBOMSG_BOOST_SERIALIZATION_ACHCOMMAND_H
#define HUBOMSG_BOOST_SERIALIZATION_ACHCOMMAND_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <hubomsg/AchCommand.h>

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::hubomsg::AchCommand_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("commandName",m.commandName);
    a & make_nvp("jointName",m.jointName);
}

} // namespace serialization
} // namespace boost

#endif // HUBOMSG_BOOST_SERIALIZATION_ACHCOMMAND_H

