/* Auto-generated by genmsg_cpp for file /home/hubo/maestro/hubomsg/msg/CanMessage.msg */
#ifndef HUBOMSG_BOOST_SERIALIZATION_CANMESSAGE_H
#define HUBOMSG_BOOST_SERIALIZATION_CANMESSAGE_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <hubomsg/boost/CanMessage.h>

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::hubomsg::CanMessage_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("mType",m.mType);
    a & make_nvp("cmdType",m.cmdType);
    a & make_nvp("bno",m.bno);
    a & make_nvp("r1",m.r1);
    a & make_nvp("r2",m.r2);
    a & make_nvp("r3",m.r3);
    a & make_nvp("r4",m.r4);
    a & make_nvp("r5",m.r5);
    a & make_nvp("r6",m.r6);
    a & make_nvp("r7",m.r7);
    a & make_nvp("r8",m.r8);
}

} // namespace serialization
} // namespace boost

#endif // HUBOMSG_BOOST_SERIALIZATION_CANMESSAGE_H

