/* Auto-generated by genmsg_cpp for file /opt/ros/fuerte/stacks/maestro/hubomsg/msg/HuboFT.msg */
#ifndef HUBOMSG_BOOST_SERIALIZATION_HUBOFT_H
#define HUBOMSG_BOOST_SERIALIZATION_HUBOFT_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <hubomsg/HuboFT.h>

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::hubomsg::HuboFT_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("Mx",m.Mx);
    a & make_nvp("My",m.My);
    a & make_nvp("Fz",m.Fz);
}

} // namespace serialization
} // namespace boost

#endif // HUBOMSG_BOOST_SERIALIZATION_HUBOFT_H

