/* Auto-generated by genmsg_cpp for file /opt/ros/fuerte/stacks/maestro/hubomsg/msg/HuboIMU.msg */
#ifndef HUBOMSG_BOOST_SERIALIZATION_HUBOIMU_H
#define HUBOMSG_BOOST_SERIALIZATION_HUBOIMU_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <hubomsg/HuboIMU.h>

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::hubomsg::HuboIMU_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("x_acceleration",m.x_acceleration);
    a & make_nvp("y_acceleration",m.y_acceleration);
    a & make_nvp("z_acceleration",m.z_acceleration);
    a & make_nvp("x_rotation",m.x_rotation);
    a & make_nvp("y_rotation",m.y_rotation);
}

} // namespace serialization
} // namespace boost

#endif // HUBOMSG_BOOST_SERIALIZATION_HUBOIMU_H

