/* Auto-generated by genmsg_cpp for file /opt/ros/fuerte/stacks/maestro/hubomsg/msg/HuboJointCommand.msg */
#ifndef HUBOMSG_BOOST_SERIALIZATION_HUBOJOINTCOMMAND_H
#define HUBOMSG_BOOST_SERIALIZATION_HUBOJOINTCOMMAND_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <hubomsg/HuboJointCommand.h>

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::hubomsg::HuboJointCommand_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("name",m.name);
    a & make_nvp("position",m.position);
    a & make_nvp("velocity",m.velocity);
}

} // namespace serialization
} // namespace boost

#endif // HUBOMSG_BOOST_SERIALIZATION_HUBOJOINTCOMMAND_H

