/* Auto-generated by genmsg_cpp for file /opt/ros/fuerte/stacks/maestro/hubomsg/msg/HuboHand.msg */
#ifndef HUBOMSG_BOOST_SERIALIZATION_HUBOHAND_H
#define HUBOMSG_BOOST_SERIALIZATION_HUBOHAND_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <hubomsg/HuboHand.h>
#include "hubomsg/boost/HuboJointState.h"
#include "hubomsg/boost/HuboJointState.h"
#include "hubomsg/boost/HuboJointState.h"
#include "hubomsg/boost/HuboJointState.h"
#include "hubomsg/boost/HuboJointState.h"

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::hubomsg::HuboHand_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("thumb",m.thumb);
    a & make_nvp("index",m.index);
    a & make_nvp("middle",m.middle);
    a & make_nvp("ring",m.ring);
    a & make_nvp("pinky",m.pinky);
}

} // namespace serialization
} // namespace boost

#endif // HUBOMSG_BOOST_SERIALIZATION_HUBOHAND_H

