/* Auto-generated by genmsg_cpp for file /opt/ros/diamondback/stacks/hubo_ctrl/msg/HuboCtrl.msg */
#ifndef HUBO_CTRL_MESSAGE_HUBOCTRL_H
#define HUBO_CTRL_MESSAGE_HUBOCTRL_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"

#include "std_msgs/Header.h"

namespace hubo_ctrl
{
template <class ContainerAllocator>
struct HuboCtrl_ : public ros::Message
{
  typedef HuboCtrl_<ContainerAllocator> Type;

  HuboCtrl_()
  : header()
  , joint_name()
  , angle(0.0)
  , velocity(0.0)
  {
  }

  HuboCtrl_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , joint_name(_alloc)
  , angle(0.0)
  , velocity(0.0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _joint_name_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  joint_name;

  typedef double _angle_type;
  double angle;

  typedef double _velocity_type;
  double velocity;


private:
  static const char* __s_getDataType_() { return "hubo_ctrl/HuboCtrl"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "abb97f28abdd675e0b3c025707b5eac8"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "Header header\n\
string joint_name\n\
float64 angle\n\
float64 velocity\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, header);
    ros::serialization::serialize(stream, joint_name);
    ros::serialization::serialize(stream, angle);
    ros::serialization::serialize(stream, velocity);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, header);
    ros::serialization::deserialize(stream, joint_name);
    ros::serialization::deserialize(stream, angle);
    ros::serialization::deserialize(stream, velocity);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(header);
    size += ros::serialization::serializationLength(joint_name);
    size += ros::serialization::serializationLength(angle);
    size += ros::serialization::serializationLength(velocity);
    return size;
  }

  typedef boost::shared_ptr< ::hubo_ctrl::HuboCtrl_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hubo_ctrl::HuboCtrl_<ContainerAllocator>  const> ConstPtr;
}; // struct HuboCtrl
typedef  ::hubo_ctrl::HuboCtrl_<std::allocator<void> > HuboCtrl;

typedef boost::shared_ptr< ::hubo_ctrl::HuboCtrl> HuboCtrlPtr;
typedef boost::shared_ptr< ::hubo_ctrl::HuboCtrl const> HuboCtrlConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::hubo_ctrl::HuboCtrl_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::hubo_ctrl::HuboCtrl_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace hubo_ctrl

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::hubo_ctrl::HuboCtrl_<ContainerAllocator> > {
  static const char* value() 
  {
    return "abb97f28abdd675e0b3c025707b5eac8";
  }

  static const char* value(const  ::hubo_ctrl::HuboCtrl_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xabb97f28abdd675eULL;
  static const uint64_t static_value2 = 0x0b3c025707b5eac8ULL;
};

template<class ContainerAllocator>
struct DataType< ::hubo_ctrl::HuboCtrl_<ContainerAllocator> > {
  static const char* value() 
  {
    return "hubo_ctrl/HuboCtrl";
  }

  static const char* value(const  ::hubo_ctrl::HuboCtrl_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::hubo_ctrl::HuboCtrl_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
string joint_name\n\
float64 angle\n\
float64 velocity\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::hubo_ctrl::HuboCtrl_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::hubo_ctrl::HuboCtrl_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::hubo_ctrl::HuboCtrl_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::hubo_ctrl::HuboCtrl_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.joint_name);
    stream.next(m.angle);
    stream.next(m.velocity);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct HuboCtrl_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hubo_ctrl::HuboCtrl_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::hubo_ctrl::HuboCtrl_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "joint_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.joint_name);
    s << indent << "angle: ";
    Printer<double>::stream(s, indent + "  ", v.angle);
    s << indent << "velocity: ";
    Printer<double>::stream(s, indent + "  ", v.velocity);
  }
};


} // namespace message_operations
} // namespace ros

#endif // HUBO_CTRL_MESSAGE_HUBOCTRL_H

