//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by RainbowGUI.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_RAINBOWGUI_DIALOG           102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDR_MAINFRAME                   128
#define IDD_JOINTS_DIALOG               130
#define IDD_SENSOR_DIALOG               131
#define IDD_WALKING_DIALOG              132
#define IDD_INITHUBO2_DIALOG            134
#define IDD_USER_DIALOG                 135
#define IDD_JMC_DIALOG                  136
#define IDD_PRESET_DIALOG               137
#define IDD_LSTATUS_DIALOG              138
#define IDD_USTATUS_DIALOG              139
#define IDC_RTXONOFF                    1000
#define IDC_LOADPARAM                   1001
#define IDC_CHECKDEVICE                 1002
#define IDC_CONTROLONOFF                1003
#define IDC_EXIT                        1004
#define IDC_PROPERTYSHEET               1005
#define IDC_JOINTSEL                    1007
#define IDC_STORE                       1008
#define IDC_SAVE                        1009
#define IDC_HDREDUCTION                 1010
#define IDC_FTSEL                       1011
#define IDC_PULLEYDRIVE                 1012
#define IDC_GOINITPOS                   1012
#define IDC_PULLEYDRIVEN                1013
#define IDC_UPPERINITPOS                1013
#define IDC_ENCODERPPR                  1014
#define IDC_LOWERINITPOS                1014
#define IDC_RIGHTINVERSE                1014
#define IDC_ALLINITPOS                  1015
#define IDC_LEFTINVERSE                 1015
#define IDC_OFFSETPOS                   1016
#define IDC_GOOFFSETPOS                 1017
#define IDC_ENCODERZERO                 1018
#define IDC_SAVEOFFSET                  1019
#define IDC_RMX                         1020
#define IDC_FTNULLING                   1021
#define IDC_RHR                         1021
#define IDC_FOOTANGLENULLING            1022
#define IDC_RHP                         1022
#define IDC_IMUNULLING                  1023
#define IDC_RKN                         1023
#define IDC_ANKLEONOFF                  1024
#define IDC_RMY                         1024
#define IDC_DECOUPLE00                  1024
#define IDC_WALKREADY                   1025
#define IDC_RFZ                         1025
#define IDC_DECOUPLE01                  1025
#define IDC_ZMPINIT                     1026
#define IDC_LMX                         1026
#define IDC_DECOUPLE02                  1026
#define IDC_LMY                         1027
#define IDC_DECOUPLE10                  1027
#define IDC_DATASAVE                    1027
#define IDC_SWAY                        1028
#define IDC_LFZ                         1028
#define IDC_DECOUPLE11                  1028
#define IDC_RROLL                       1029
#define IDC_DECOUPLE12                  1029
#define IDC_RANGEONOFF                  1029
#define IDC_RPITCH                      1030
#define IDC_DECOUPLE20                  1030
#define IDC_LROLL                       1031
#define IDC_DECOUPLE21                  1031
#define IDC_LPITCH                      1032
#define IDC_DECOUPLE22                  1032
#define IDC_ROLL                        1033
#define IDC_FTCUTOFF                    1033
#define IDC_RSR                         1034
#define IDC_IMUSEL                      1034
#define IDC_RWMX                        1034
#define IDC_PITCH                       1035
#define IDC_FTSTORE                     1035
#define IDC_REB                         1036
#define IDC_IMUSTORE                    1036
#define IDC_RWMY                        1036
#define IDC_ROLLV                       1037
#define IDC_SFROLL                      1037
#define IDC_WALKINGSET                  1038
#define IDC_RWP                         1038
#define IDC_SFPITCH                     1038
#define IDC_RWFZ                        1038
#define IDC_PLUSROTATION                1039
#define IDC_PITCHV                      1039
#define IDC_ZEROROTATION                1040
#define IDC_LSR                         1040
#define IDC_LWMX                        1040
#define IDC_MINUSROTATION               1041
#define IDC_ZMPX                        1041
#define IDC_PLUSSIDE                    1042
#define IDC_ZMPY                        1042
#define IDC_ZEROSIDE                    1043
#define IDC_RZMPX                       1043
#define IDC_MINUSSIDE                   1044
#define IDC_RZMPY                       1044
#define IDC_HOLD                        1045
#define IDC_LZMPX                       1045
#define IDC_DSP                         1046
#define IDC_LZMPY                       1046
#define IDC_STARTSWAY                   1047
#define IDC_RF4                         1047
#define IDC_LWMY                        1047
#define IDC_STOPSWAY                    1048
#define IDC_RF5                         1048
#define IDC_LWFZ                        1048
#define IDC_PERIOD                      1049
#define IDC_LF1                         1049
#define IDC_FORWARD                     1050
#define IDC_LF2                         1050
#define IDC_SIDE                        1051
#define IDC_LF3                         1051
#define IDC_ROTATION                    1052
#define IDC_LF4                         1052
#define IDC_STEPCOUNT                   1053
#define IDC_LF5                         1053
#define IDC_GO                          1054
#define IDC_NKY                         1054
#define IDC_MOTIONLIST                  1055
#define IDC_NK1                         1055
#define IDC_MOTION                      1056
#define IDC_NK2                         1056
#define IDC_WST                         1057
#define IDC_STOP                        1057
#define IDC_RHY                         1058
#define IDC_DEMOLIST                    1058
#define IDC_RAP                         1059
#define IDC_DEMO1                       1059
#define IDC_ENCRESOLUTION               1059
#define IDC_RAR                         1060
#define IDC_DEMO2                       1060
#define IDC_MOTORDIR                    1060
#define IDC_RSP                         1061
#define IDC_DEMO3                       1061
#define IDC_RSY                         1062
#define IDC_DEMO4                       1062
#define IDC_RWY                         1063
#define IDC_HANDLIST                    1063
#define IDC_LHY                         1064
#define IDC_HAND1                       1064
#define IDC_LHR                         1065
#define IDC_HAND2                       1065
#define IDC_LHP                         1066
#define IDC_HAND3                       1066
#define IDC_LKN                         1067
#define IDC_HAND4                       1067
#define IDC_LAP                         1068
#define IDC_LAR                         1069
#define IDC_LSP                         1070
#define IDC_LSY                         1071
#define IDC_PLUSCURRENT                 1071
#define IDC_LEB                         1072
#define IDC_MINUSCURRENT                1072
#define IDC_LWY                         1073
#define IDC_LWP                         1074
#define IDC_RF1                         1075
#define IDC_RF2                         1076
#define IDC_RF3                         1077
#define IDC_RIGHTTASKX                  1078
#define IDC_RIGHTTASKY                  1079
#define IDC_RIGHTTASKZ                  1080
#define IDC_LEFTTASKX                   1081
#define IDC_PRESETSEL                   1082
#define IDC_GETCURRENT                  1083
#define IDC_LEFTTASKY                   1084
#define IDC_LEFTTASKZ                   1085
#define IDC_TIME                        1086
#define IDC_GOPOS                       1087
#define IDC_SETENCODER                  1089
#define IDC_DEADZONE                    1090
#define IDC_LOWERLIMIT                  1091
#define IDC_SETPOSLIMIT                 1092
#define IDC_UPPERLIMIT                  1093
#define IDC_MAXVEL                      1094
#define IDC_MAXACC                      1095
#define IDC_SETMAXVELACC                1097
#define IDC_JAMSATTIME                  1099
#define IDC_PWMSATTIME                  1100
#define IDC_SETSATURATION               1101
#define IDC_JAMDUTY                     1102
#define IDC_IERR                        1103
#define IDC_BERR                        1104
#define IDC_EERR                        1105
#define IDC_PGAIN                       1106
#define IDC_SETERRBOUND                 1107
#define IDC_HOMEMAXVEL                  1108
#define IDC_HOMEMAXACC                  1109
#define IDC_TEST1                       1109
#define IDC_HOMESEARCHDIR               1110
#define IDC_TEST2                       1110
#define IDC_HOME_RHY                    1110
#define IDC_HOMEOFFSET                  1111
#define IDC_TEST3                       1111
#define IDC_HOME_RHR                    1111
#define IDC_HOMELIMITREV                1112
#define IDC_TEST4                       1112
#define IDC_HOME_RHP                    1112
#define IDC_SETHOMEVELACC               1113
#define IDC_TEST5                       1113
#define IDC_HOME_RKN                    1113
#define IDC_HOME_RAP                    1114
#define IDC_SETHOMEPARA                 1115
#define IDC_HOME_RAR                    1115
#define IDC_IGAIN                       1116
#define IDC_HOME_LHY                    1116
#define IDC_DGAIN                       1117
#define IDC_HOME_LHR                    1117
#define IDC_SETMODE                     1118
#define IDC_HOME_LHP                    1118
#define IDC_SETGAIN                     1119
#define IDC_HOME_LKN                    1119
#define IDC_PWMDUTY                     1120
#define IDC_HOME_LAP                    1120
#define IDC_HOMESEARCHMODE              1121
#define IDC_HOME_LAR                    1121
#define IDC_HOMEPWM                     1122
#define IDC_JAM_RHY                     1122
#define IDC_JAM_RHR                     1123
#define IDC_JAM_RHP                     1124
#define IDC_JAM_RKN                     1125
#define IDC_JAM_RAP                     1126
#define IDC_JAM_RAR                     1127
#define IDC_JAM_LHY                     1128
#define IDC_JAM_LHR                     1129
#define IDC_JAM_LHP                     1130
#define IDC_JAM_LKN                     1131
#define IDC_JAM_LAP                     1132
#define IDC_JAM_LAR                     1133
#define IDC_PWM_RHY                     1134
#define IDC_PWM_RHR                     1135
#define IDC_PWM_RHP                     1136
#define IDC_PWM_RKN                     1137
#define IDC_PWM_RAP                     1138
#define IDC_PWM_RAR                     1139
#define IDC_PWM_LHY                     1140
#define IDC_PWM_LHR                     1141
#define IDC_PWM_LHP                     1142
#define IDC_PWM_LKN                     1143
#define IDC_PWM_LAP                     1144
#define IDC_PWM_LAR                     1145
#define IDC_BIG_RHY                     1146
#define IDC_BIG_RHR                     1147
#define IDC_BIG_RHP                     1148
#define IDC_BIG_RKN                     1149
#define IDC_BIG_RAP                     1150
#define IDC_BIG_RAR                     1151
#define IDC_BIG_LHY                     1152
#define IDC_BIG_LHR                     1153
#define IDC_BIG_LHP                     1154
#define IDC_BIG_LKN                     1155
#define IDC_BIG_LAP                     1156
#define IDC_BIG_LAR                     1157
#define IDC_ENC_RHY                     1158
#define IDC_ENC_RHR                     1159
#define IDC_ENC_RHP                     1160
#define IDC_ENC_RKN                     1161
#define IDC_ENC_RAP                     1162
#define IDC_ENC_RAR                     1163
#define IDC_ENC_LHY                     1164
#define IDC_ENC_LHR                     1165
#define IDC_ENC_LHP                     1166
#define IDC_ENC_LKN                     1167
#define IDC_ENC_LAP                     1168
#define IDC_ENC_LAR                     1169
#define IDC_DRV_RHY                     1170
#define IDC_DRV_RHR                     1171
#define IDC_DRV_RHP                     1172
#define IDC_DRV_RKN                     1173
#define IDC_DRV_RAP                     1174
#define IDC_DRV_RAR                     1175
#define IDC_DRV_LHY                     1176
#define IDC_DRV_LHR                     1177
#define IDC_DRV_LHP                     1178
#define IDC_DRV_LKN                     1179
#define IDC_DRV_LAP                     1180
#define IDC_DRV_LAR                     1181
#define IDC_M0E_RHY                     1182
#define IDC_M0E_RHR                     1183
#define IDC_M0E_RHP                     1184
#define IDC_M0E_RKN                     1185
#define IDC_M0E_RAP                     1186
#define IDC_M0E_RAR                     1187
#define IDC_M0E_LHY                     1188
#define IDC_M0E_LHR                     1189
#define IDC_M0E_LHP                     1190
#define IDC_M0E_LKN                     1191
#define IDC_M0E_LAP                     1192
#define IDC_M0E_LAR                     1193
#define IDC_M1E_RHY                     1194
#define IDC_M1E_RHR                     1195
#define IDC_M1E_RHP                     1196
#define IDC_M1E_RKN                     1197
#define IDC_M1E_RAP                     1198
#define IDC_M1E_RAR                     1199
#define IDC_M1E_LHY                     1200
#define IDC_M1E_LHR                     1201
#define IDC_M1E_LHP                     1202
#define IDC_M1E_LKN                     1203
#define IDC_M1E_LAP                     1204
#define IDC_M1E_LAR                     1205
#define IDC_UPL_RHY                     1206
#define IDC_UPL_RHR                     1207
#define IDC_UPL_RHP                     1208
#define IDC_UPL_RKN                     1209
#define IDC_UPL_RAP                     1210
#define IDC_UPL_RAR                     1211
#define IDC_UPL_LHY                     1212
#define IDC_UPL_LHR                     1213
#define IDC_UPL_LHP                     1214
#define IDC_UPL_LKN                     1215
#define IDC_UPL_LAP                     1216
#define IDC_UPL_LAR                     1217
#define IDC_LOL_RHY                     1218
#define IDC_LOL_RHR                     1219
#define IDC_LOL_RHP                     1220
#define IDC_LOL_RKN                     1221
#define IDC_LOL_RAP                     1222
#define IDC_LOL_RAR                     1223
#define IDC_LOL_LHY                     1224
#define IDC_LOL_LHR                     1225
#define IDC_LOL_LHP                     1226
#define IDC_LOL_LKN                     1227
#define IDC_LOL_LAP                     1228
#define IDC_LOL_LAR                     1229
#define IDC_BUTTON1                     1230
#define IDC_PITCH_OVERALL               1231
#define IDC_PITCH_P                     1232
#define IDC_PITCH_V                     1233
#define IDC_ROLL_OVERALL                1234
#define IDC_ROLL_P                      1235
#define IDC_ROLL_V                      1236
#define IDC_ROLL_DAMPING_SET            1237
#define IDC_PITCH_DAMPING_SET           1238
#define IDC_HOME_RSP                    1239
#define IDC_HOME_RSR                    1240
#define IDC_HOME_RSY                    1241
#define IDC_HOME_REB                    1242
#define IDC_HOME_RWY                    1243
#define IDC_HOME_RWP                    1244
#define IDC_HOME_LSP                    1245
#define IDC_HOME_LSR                    1246
#define IDC_HOME_LSY                    1247
#define IDC_HOME_LEB                    1248
#define IDC_HOME_LWY                    1249
#define IDC_HOME_LWP                    1250
#define IDC_JAM_RSP                     1251
#define IDC_JAM_RSR                     1252
#define IDC_JAM_RSY                     1253
#define IDC_JAM_REB                     1254
#define IDC_JAM_RWY                     1255
#define IDC_JAM_RWP                     1256
#define IDC_JAM_LSP                     1257
#define IDC_JAM_LSR                     1258
#define IDC_JAM_LSY                     1259
#define IDC_JAM_LEB                     1260
#define IDC_JAM_LWY                     1261
#define IDC_JAM_LWP                     1262
#define IDC_PWM_RSP                     1263
#define IDC_PWM_RSR                     1264
#define IDC_PWM_RSY                     1265
#define IDC_PWM_REB                     1266
#define IDC_PWM_RWY                     1267
#define IDC_PWM_RWP                     1268
#define IDC_PWM_LSP                     1269
#define IDC_PWM_LSR                     1270
#define IDC_PWM_LSY                     1271
#define IDC_PWM_LEB                     1272
#define IDC_PWM_LWY                     1273
#define IDC_PWM_LWP                     1274
#define IDC_BIG_RSP                     1275
#define IDC_BIG_RSR                     1276
#define IDC_BIG_RSY                     1277
#define IDC_BIG_REB                     1278
#define IDC_BIG_RWY                     1279
#define IDC_BIG_RWP                     1280
#define IDC_BIG_LSP                     1281
#define IDC_BIG_LSR                     1282
#define IDC_BIG_LSY                     1283
#define IDC_BIG_LEB                     1284
#define IDC_BIG_LWY                     1285
#define IDC_BIG_LWP                     1286
#define IDC_ENC_RSP                     1287
#define IDC_ENC_RSR                     1288
#define IDC_ENC_RSY                     1289
#define IDC_ENC_REB                     1290
#define IDC_ENC_RWY                     1291
#define IDC_ENC_RWP                     1292
#define IDC_ENC_LSP                     1293
#define IDC_ENC_LSR                     1294
#define IDC_ENC_LSY                     1295
#define IDC_ENC_LEB                     1296
#define IDC_ENC_LWY                     1297
#define IDC_ENC_LWP                     1298
#define IDC_DRV_RSP                     1299
#define IDC_DRV_RSR                     1300
#define IDC_DRV_RSY                     1301
#define IDC_DRV_REB                     1302
#define IDC_DRV_RWY                     1303
#define IDC_DRV_RWP                     1304
#define IDC_DRV_LSP                     1305
#define IDC_DRV_LSR                     1306
#define IDC_DRV_LSY                     1307
#define IDC_DRV_LEB                     1308
#define IDC_DRV_LWY                     1309
#define IDC_DRV_LWP                     1310
#define IDC_M0E_RSP                     1311
#define IDC_M0E_RSR                     1312
#define IDC_M0E_RSY                     1313
#define IDC_M0E_REB                     1314
#define IDC_M0E_RWY                     1315
#define IDC_M0E_RWP                     1316
#define IDC_M0E_LSP                     1317
#define IDC_M0E_LSR                     1318
#define IDC_M0E_LSY                     1319
#define IDC_M0E_LEB                     1320
#define IDC_M0E_LWY                     1321
#define IDC_M0E_LWP                     1322
#define IDC_M1E_RSP                     1323
#define IDC_M1E_RSR                     1324
#define IDC_M1E_RSY                     1325
#define IDC_M1E_REB                     1326
#define IDC_M1E_RWY                     1327
#define IDC_M1E_RWP                     1328
#define IDC_M1E_LSP                     1329
#define IDC_M1E_LSR                     1330
#define IDC_M1E_LSY                     1331
#define IDC_M1E_LEB                     1332
#define IDC_M1E_LWY                     1333
#define IDC_M1E_LWP                     1334
#define IDC_UPL_RSP                     1335
#define IDC_UPL_RSR                     1336
#define IDC_UPL_RSY                     1337
#define IDC_UPL_REB                     1338
#define IDC_UPL_RWY                     1339
#define IDC_UPL_RWP                     1340
#define IDC_UPL_LSP                     1341
#define IDC_UPL_LSR                     1342
#define IDC_UPL_LSY                     1343
#define IDC_UPL_LEB                     1344
#define IDC_UPL_LWY                     1345
#define IDC_UPL_LWP                     1346
#define IDC_LOL_RSP                     1347
#define IDC_LOL_RSR                     1348
#define IDC_LOL_RSY                     1349
#define IDC_LOL_REB                     1350
#define IDC_LOL_RWY                     1351
#define IDC_LOL_RWP                     1352
#define IDC_LOL_LSP                     1353
#define IDC_LOL_LSR                     1354
#define IDC_LOL_LSY                     1355
#define IDC_LOL_LEB                     1356
#define IDC_LOL_LWY                     1357
#define IDC_LOL_LWP                     1358
#define IDC_CURRENT                     1360

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        140
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1361
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
