#ifndef _NAMES_H
#define _NAMES_H

enum PROPERTY {
	POSITION, VELOCITY, TEMPERATURE, CURRENT, HOMED, ZEROED, ENABLED,
	ERRORED, JAM_ERROR, PWM_SATURATED_ERROR, BIG_ERROR, ENC_ERROR, DRIVE_FAULT_ERROR,
	POS_MIN_ERROR, POS_MAX_ERROR, VELOCITY_ERROR, ACCELERATION_ERROR, TEMP_ERROR,
	X_ACCEL, Y_ACCEL, Z_ACCEL, X_ROTAT, Y_ROTAT,
	M_X, M_Y, F_Z
};

enum COMMAND {
	ENABLE, ENABLEALL,
	DISABLE, DISABLEALL,
	RESET, RESETALL,
	HOME, HOMEALL,
	INITSENSORS,
	UPDATE
};

#endif
